import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import type { Category, SeedWord } from '../src/data/schema';

const RESEARCH = join(import.meta.dir, '..', 'docs', 'ogden-research', 'basic-english-850.json');
const OUT = join(import.meta.dir, '..', 'src', 'data', 'words.seed.ts');

const UK_TO_US: Record<string, string> = {
  behaviour: 'behavior',
  colour: 'color',
  harbour: 'harbor',
  humour: 'humor',
  plough: 'plow',
  grey: 'gray',
};

const OPERATORS_18 = [
  'come', 'get', 'give', 'go', 'keep', 'let', 'make', 'put', 'seem', 'take',
  'be', 'do', 'have', 'say', 'see', 'send', 'may', 'will',
];

type RawData = {
  source: string;
  license: string;
  categories: Record<Category, string[]>;
};

const raw = JSON.parse(readFileSync(RESEARCH, 'utf-8')) as RawData;

const seeds: SeedWord[] = [];
const seenIds = new Set<string>();

for (const [category, words] of Object.entries(raw.categories) as Array<[Category, string[]]>) {
  for (const headword of words) {
    const id = headword.toLowerCase().replace(/[^a-z0-9]/g, '_');
    if (seenIds.has(id)) {
      throw new Error(`Duplicate id: ${id} (headword=${headword}, category=${category})`);
    }
    seenIds.add(id);

    const spelling_uk = headword;
    const spelling_us = UK_TO_US[headword] ?? headword;
    const is_18_operators = category === 'operations' && OPERATORS_18.includes(headword);

    seeds.push({ id, headword, spelling_uk, spelling_us, category, is_18_operators });
  }
}

const ops18Count = seeds.filter((w) => w.is_18_operators).length;
if (ops18Count !== 18) {
  throw new Error(`Expected 18 operators, got ${ops18Count}`);
}

const banner = `// AUTO-GENERATED by scripts/build-seed.ts — do not edit by hand.
// Source: ${raw.source}
// License: ${raw.license}

import type { SeedWord } from './schema';

export const SEED_WORDS: readonly SeedWord[] = ${JSON.stringify(seeds, null, 2)} as const;
`;

writeFileSync(OUT, banner, 'utf-8');

console.log(`Wrote ${seeds.length} words to ${OUT}`);
console.log(`18 operators: ${ops18Count}/18`);
const byCat = seeds.reduce<Record<string, number>>((acc, w) => {
  acc[w.category] = (acc[w.category] ?? 0) + 1;
  return acc;
}, {});
console.log('By category:', byCat);
