/**
 * Merge generated/reviewed content batches into src/data/words.ts.
 *
 * - Reads all data/generated/*.json
 * - Joins with src/data/words.seed.ts (headword, spelling, category, is_18_operators)
 * - For headwords without generated content, fills placeholder fields so the UI can still render.
 * - Writes src/data/words.ts.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { WordSchema, type Word } from '../src/data/schema';
import { SEED_WORDS } from '../src/data/words.seed';

const ROOT = join(import.meta.dir, '..');
const GEN_DIR = join(ROOT, 'data', 'generated');
const OUT = join(ROOT, 'src', 'data', 'words.ts');

interface GeneratedEntry {
  id: string;
  definition_en: string;
  gloss_zh_tw: string;
  example_en: string;
  example_zh_tw: string;
  synonyms: string[];
  notes?: string;
}

interface GeneratedFile {
  category: string;
  batch: number;
  results: GeneratedEntry[];
}

const generatedById = new Map<string, GeneratedEntry>();
for (const file of readdirSync(GEN_DIR).filter((f) => f.endsWith('.json')).sort()) {
  const data = JSON.parse(readFileSync(join(GEN_DIR, file), 'utf-8')) as GeneratedFile;
  for (const entry of data.results) {
    if (generatedById.has(entry.id)) {
      console.warn(`  duplicate id across batches: ${entry.id} (latest from ${file} wins)`);
    }
    generatedById.set(entry.id, entry);
  }
}

const words: Word[] = SEED_WORDS.map((seed) => {
  const gen = generatedById.get(seed.id);
  const base = {
    id: seed.id,
    headword: seed.headword,
    spelling_uk: seed.spelling_uk,
    spelling_us: seed.spelling_us,
    category: seed.category,
    is_18_operators: seed.is_18_operators,
  };
  if (gen) {
    return WordSchema.parse({
      ...base,
      definition_en: gen.definition_en,
      gloss_zh_tw: gen.gloss_zh_tw,
      example_en: gen.example_en,
      example_zh_tw: gen.example_zh_tw,
      synonyms: gen.synonyms,
      ...(gen.notes ? { notes: gen.notes } : {}),
    });
  }
  return WordSchema.parse({
    ...base,
    definition_en: `(definition pending)`,
    gloss_zh_tw: `（釋義待補）`,
    example_en: `(example pending — uses "${seed.headword}")`,
    example_zh_tw: `（例句待補）`,
    synonyms: [],
    notes: 'PLACEHOLDER',
  });
});

const ready = words.filter((w) => w.notes !== 'PLACEHOLDER').length;
const pending = words.length - ready;

const banner = `// AUTO-GENERATED by scripts/merge-reviewed.ts — do not edit by hand.
// ${ready} of ${words.length} words have reviewed content; ${pending} still placeholder.
//
// Content license: CC BY-SA 4.0 (see LICENSE-CONTENT.md at repo root)
// Copyright (c) 2026 yelban (https://github.com/yelban/Ogden)
// Vocabulary structure derived from Wiktionary Appendix:Basic_English_word_list (CC BY-SA 4.0).

import type { Word } from './schema';

export const WORDS: readonly Word[] = ${JSON.stringify(words, null, 2)} as const;
`;

writeFileSync(OUT, banner, 'utf-8');
console.log(`Wrote ${words.length} words to ${OUT}`);
console.log(`Reviewed: ${ready}  ·  Placeholder: ${pending}`);
